In [1]:
import pandas as pd
import numpy as np
import os

In [20]:
xtrain=np.load(r'C:/Users/409/Desktop/新增資料夾/all/X_train1.npy',mmap_mode="r")

In [21]:
xtest=np.load(r'C:/Users/409/Desktop/新增資料夾/all/x_test1.npy',mmap_mode="r")

In [22]:
ytrain=np.load(r'C:/Users/409/Desktop/新增資料夾/all/y_train1.npyxtrain', mmap_mode="r")
ytrain

memmap([0, 1, 0, ..., 0, 0, 1], dtype=int64)

In [45]:
X_train_normalize=xtrain.astype('float32')/255
X_test_normalize=xtest.astype('float32')/255

In [47]:
from sklearn.model_selection import train_test_split
#split the data with 25% in each set
X1, X2, y1, y2 = train_test_split(xtrain, ytrain, random_state=0, test_size=0.25)

In [24]:
from keras.utils import np_utils
print(X_train_normalize.shape)
print(X_test_normalize.shape)

(14424, 224, 224, 3)
(3000, 224, 224, 3)


In [25]:
ytrain

memmap([0, 1, 0, ..., 0, 0, 1], dtype=int64)

In [26]:
from keras import layers
from keras import models
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Conv2D, MaxPooling2D, ZeroPadding2D
from keras import regularizers
from keras.preprocessing.image import ImageDataGenerator
from keras.utils import to_categorical

In [27]:
model=Sequential()
model.add(layers.Conv2D(32,kernel_size=(3,3),activation='relu',input_shape=(224,224,3)))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(32,(3,3),activation='relu'))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(64,(3,3),activation='relu'))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(64,(3,3),activation='relu'))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(128,(3,3),activation='relu'))
model.add(layers.Flatten())
model.add(layers.Dense(64,kernel_regularizer=regularizers.l1_l2(l1=0.001, l2=0.001),activation='relu'))
model.add(layers.Dense(3,activation='softmax'))

In [28]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_6 (Conv2D)            (None, 222, 222, 32)      896       
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 111, 111, 32)      0         
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 109, 109, 32)      9248      
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 54, 54, 32)        0         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 52, 52, 64)        18496     
_________________________________________________________________
max_pooling2d_7 (MaxPooling2 (None, 26, 26, 64)        0         
_________________________________________________________________
conv2d_9 (Conv2D)            (None, 24, 24, 64)        36928     
__________

In [29]:
model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

In [30]:
ytrain=to_categorical(ytrain)

In [31]:
ytrain

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]], dtype=float32)

In [32]:
model.fit(X_train_normalize,ytrain,epochs=25,batch_size=64,validation_split=0.1)

Train on 12981 samples, validate on 1443 samples
Epoch 1/25
12981/12981 [==============================] - 18s 1ms/step - loss: 1.4787 - acc: 0.6040 - val_loss: 1.1267 - val_acc: 0.7062
Epoch 2/25
12981/12981 [==============================] - 16s 1ms/step - loss: 1.1233 - acc: 0.6965 - val_loss: 1.3551 - val_acc: 0.6299
Epoch 3/25
12981/12981 [==============================] - 16s 1ms/step - loss: 1.0746 - acc: 0.7260 - val_loss: 1.0841 - val_acc: 0.7318
Epoch 4/25
12981/12981 [==============================] - 16s 1ms/step - loss: 1.0420 - acc: 0.7402 - val_loss: 0.9862 - val_acc: 0.7720
Epoch 5/25
12981/12981 [==============================] - 16s 1ms/step - loss: 1.0058 - acc: 0.7595 - val_loss: 0.9723 - val_acc: 0.7769
Epoch 6/25
12981/12981 [==============================] - 16s 1ms/step - loss: 0.9791 - acc: 0.7702 - val_loss: 0.9710 - val_acc: 0.7769
Epoch 7/25
12981/12981 [==============================] - 16s 1ms/step - loss: 0.9591 - acc: 0.7828 - val_loss: 0.9245 - val_acc:

In [37]:
model.fit(X_train_normalize,ytrain,epochs=5,batch_size=256,validation_split=0.1)

Train on 12981 samples, validate on 1443 samples
Epoch 1/5
12981/12981 [==============================] - 15s 1ms/step - loss: 0.8987 - acc: 0.8094 - val_loss: 1.0434 - val_acc: 0.7852
Epoch 2/5
12981/12981 [==============================] - 14s 1ms/step - loss: 0.9035 - acc: 0.8083 - val_loss: 0.9111 - val_acc: 0.8087
Epoch 3/5
12981/12981 [==============================] - 15s 1ms/step - loss: 0.8932 - acc: 0.8121 - val_loss: 0.9688 - val_acc: 0.7949
Epoch 4/5
12981/12981 [==============================] - 15s 1ms/step - loss: 0.8857 - acc: 0.8157 - val_loss: 0.9003 - val_acc: 0.8150
Epoch 5/5
12981/12981 [==============================] - 15s 1ms/step - loss: 0.8797 - acc: 0.8176 - val_loss: 0.9428 - val_acc: 0.7956


In [33]:
Y_pred = model.predict(X_test_normalize)
Y_pred

array([[5.9396547e-07, 9.6959388e-04, 9.9902987e-01],
       [5.0071772e-04, 7.4274503e-02, 9.2522478e-01],
       [9.0300584e-01, 9.6232489e-02, 7.6166558e-04],
       ...,
       [3.8894084e-01, 6.0523909e-01, 5.8200913e-03],
       [2.1584257e-03, 3.4681404e-01, 6.5102750e-01],
       [3.6735784e-03, 1.4136043e-01, 8.5496598e-01]], dtype=float32)

In [34]:
ans = [np.argmax(i) for i in Y_pred]
print(ans.count(0), ans.count(1), ans.count(2))

966 871 1163


In [44]:
def toCSV(filename, pred):
    with open(r"C:\Users\409\Desktop\sample_submission.csv", "r") as f:
        data = f.readlines()
        data = [i.replace("\n","") for i in data]
    tmp = [str(data[i][:-1])+str(pred[i-1])+"\n" for i in range(1,len(data))]
    tmp.insert(0,data[0]+"\n")
    with open(filename, "w") as f:
        for i in tmp:
            f.write(i)
toCSV(r"C:\Users\409\Desktop\ze.csv", ans)

In [36]:
from keras.applications import VGG16

conv_base=VGG16(weights='imagenet',
                include_top=False,
                input_shape=(224,224,3))

In [37]:
from keras.layers import Input, Flatten, Dense
from keras.models import Model
from keras.layers import Dense
x = conv_base.output
x = Flatten()(x)
conv_base=Model(conv_base.input,x)
num_classes=64
x=Dense(num_classes, activation='relu')(conv_base.output)
conv_base=Model(conv_base.input,x)
num_classes=3
x=Dense(num_classes, activation='softmax')(conv_base.output)
# 重新建立模型結構
conv_base=Model(conv_base.input,x)

In [16]:
conv_base.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0         
__________

In [38]:
conv_base.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [48]:
conv_base.fit(X1,y1,epochs=10,batch_size=64)

Epoch 1/10
10818/10818 [==============================] - 81s 7ms/step - loss: 10.5042 - acc: 0.3438
Epoch 2/10
  960/10818 [=>............................] - ETA: 1:13 - loss: 10.7622 - acc: 0.3323

KeyboardInterrupt: 

In [47]:
model.fit(X_train_normalize,ytrain,epochs=5,batch_size=256)

Epoch 1/5
14424/14424 [==============================] - 15s 1ms/step - loss: 0.8108 - acc: 0.8478
Epoch 2/5
14424/14424 [==============================] - 15s 1ms/step - loss: 0.8122 - acc: 0.8498
Epoch 3/5
14424/14424 [==============================] - 15s 1ms/step - loss: 0.8114 - acc: 0.8492
Epoch 4/5
14424/14424 [==============================] - 15s 1ms/step - loss: 0.8001 - acc: 0.8560
Epoch 5/5
14424/14424 [==============================] - 15s 1ms/step - loss: 0.7957 - acc: 0.8593


In [42]:
Y_pred = model.predict(X_test_normalize)
Y_pred

array([[5.9396547e-07, 9.6959388e-04, 9.9902987e-01],
       [5.0071772e-04, 7.4274503e-02, 9.2522478e-01],
       [9.0300584e-01, 9.6232489e-02, 7.6166558e-04],
       ...,
       [3.8894084e-01, 6.0523909e-01, 5.8200913e-03],
       [2.1584257e-03, 3.4681404e-01, 6.5102750e-01],
       [3.6735784e-03, 1.4136043e-01, 8.5496598e-01]], dtype=float32)

In [43]:
ans = [np.argmax(i) for i in Y_pred]
print(ans.count(0), ans.count(1), ans.count(2))

966 871 1163
